# Generated by Django 3.0.2 on 2020-03-10 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP1', '0002_auto_20200130_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain', models.CharField(max_length=120, verbose_name='Domain')),
                ('Query', models.CharField(max_length=9200)),
                ('LastRefreshedOn', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DEMOAPP1.FAMILY'),
        ),
    ]
