# Generated by Django 3.0.2 on 2020-03-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP1', '0004_auto_20200310_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DEMOAPP1.FAMILY'),
        ),
        migrations.AlterField(
            model_name='table',
            name='Query',
            field=models.CharField(max_length=2200),
        ),
    ]
