# Generated by Django 3.0.2 on 2020-03-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP1', '0009_auto_20200310_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='family',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
