# Generated by Django 3.0.2 on 2020-03-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP1', '0010_auto_20200310_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablem',
            name='Insight',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AlterField(
            model_name='tablem',
            name='Domain',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AlterField(
            model_name='tablem',
            name='Query',
            field=models.CharField(blank=True, max_length=1200),
        ),
    ]
