# Generated by Django 3.0.2 on 2020-03-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP1', '0012_tablem_recordcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablem',
            name='Recordcount',
            field=models.CharField(blank=True, max_length=1200),
        ),
    ]
